# Generated by Django 3.1.3 on 2020-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20201110_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='website',
            name='domain_name',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='domain name'),
        ),
    ]
