# Generated by Django 3.1.3 on 2020-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_part_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cost_price_range',
            field=models.CharField(choices=[('0-50', '0-50'), ('50-100', '50-100'), ('100-150', '100-150'), ('150-200', '150-200'), ('200-300', '200-300'), ('300-500', '300-500'), ('500+', '500+'), ('500-1000', '500-1000'), ('1000-2000', '1000-2000'), ('2000+', '2000+')], default='0-50', max_length=16, verbose_name='cost price range'),
        ),
    ]
