# Generated by Django 3.1.3 on 2020-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20201111_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cost_price_range',
            field=models.CharField(choices=[('0-50', '0-50'), ('50-100', '50-100'), ('100-150', '100-150'), ('150-200', '150-200'), ('200-250', '200-250'), ('250-500', '250-500'), ('500+', '500+'), ('500-1000', '500-1000'), ('1000-2000', '1000-2000'), ('2000+', '2000+')], default='0-50', max_length=16, verbose_name='cost price range'),
        ),
    ]
