# Generated by Django 3.1.3 on 2020-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20201124_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='website',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='start date'),
        ),
    ]
