# Generated by Django 3.1.5 on 2021-01-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_websiteexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='website',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, to='parts.Manufacturer', verbose_name='manufacturers'),
        ),
    ]
