# Generated by Django 3.1.3 on 2020-11-12 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0005_auto_20201111_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='part number'),
        ),
        migrations.CreateModel(
            name='UploadProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='running', max_length=12, verbose_name='status')),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('objects_added', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
