# Generated by Django 3.1.3 on 2020-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120, verbose_name='url')),
                ('type', models.CharField(choices=[('website', 'website')], max_length=16, verbose_name='type')),
                ('method', models.CharField(max_length=60, verbose_name='method')),
            ],
        ),
    ]
