# Generated by Django 3.1.3 on 2020-12-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_auto_20201201_1405'),
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_down', models.BooleanField(blank=True, default=False, verbose_name='site is down')),
                ('error', models.TextField(verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('manufacturers', models.ManyToManyField(to='parts.Manufacturer', verbose_name='manufacturers')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to='parts.website', verbose_name='website')),
            ],
        ),
    ]
