# Generated by Django 3.1.3 on 2020-12-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_websitecrawl'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
